### ISSUE TITLE
SASS Build Task Error

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [whyleee/generator-aspnet-powermvc#4]
I'm getting this issue when trying to build the project with `grunt`.
System Specs:
- Windows 8.1 
- node v6.1.0
- npm  v3.8.9

```
C:\Users\username\Documents\Visual Studio 2015\Projects\WebApplication1\WebAppli
cation1>grunt
Running "newer:jshint" (newer) task

Running "newer-postrun:jshint:all:1:C:\Users\username\Documents\Visual Studio 20
15\Projects\WebApplication1\WebApplication1\node_modules\grunt-newer\.cache" (ne
wer-postrun) task

Running "build" task
Loading "sass.js" tasks...ERROR
>> Error: The specified procedure could not be found.
>> \\?\C:\Users\username\Documents\Visual Studio 2015\Projects\WebApplication1\W
ebApplication1\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64\b
inding.node
Warning: Task "sass" failed. Use --force to continue.

Aborted due to warnings.
```

If I try rebuiding `node-sass` I get this as well.

```
C:\Users\username\Documents\Visual Studio 2015\Projects\WebApplication1\WebAppli
cation1>npm rebuild node-sass

> node-sass@3.7.0 install C:\Users\username\Documents\Visual Studio 2015\Project
s\WebApplication1\WebApplication1\node_modules\node-sass
> node scripts/install.js


> node-sass@3.7.0 postinstall C:\Users\username\Documents\Visual Studio 2015\Pro
jects\WebApplication1\WebApplication1\node_modules\node-sass
> node scripts/build.js

"C:\Users\username\Documents\Visual Studio 2015\Projects\WebApplication1\WebAppl
ication1\node_modules\node-sass\vendor\win32-x64-48\binding.node" exists.
 testing binary.
Binary is fine; exiting.

> node-sass@1.2.3 install C:\Users\username\Documents\Visual Studio 2015\Project
s\WebApplication1\WebApplication1\node_modules\grunt-sass\node_modules\node-sass

> node scripts/install.js


> node-sass@1.2.3 postinstall C:\Users\username\Documents\Visual Studio 2015\Pro
jects\WebApplication1\WebApplication1\node_modules\grunt-sass\node_modules\node-
sass
> node scripts/build.js

`win32-x64` exists; testing
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified procedure could not be found.
\\?\C:\Users\username\Documents\Visual Studio 2015\Projects\WebApplication1\WebA
pplication1\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64\bind
ing.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\username\Documents\Visual Studio 2015\Projec
ts\WebApplication1\WebApplication1\node_modules\grunt-sass\node_modules\node-sas
s\lib\index.js:181:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "node-sass"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js
'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\username\Documents\Visual Studio 2015\Projects\WebApplicat
ion1\WebApplication1\npm-debug.log
```

Any idea why I'm getting this error?

**Comment by Giovanni-Mattucci** [comment]
Seems it was a conflict with Node + NPM version and `grunt-sass`, updated to ~1.2.0 and it compiles correctly with no errors now.

**Comment by ganiserb** [comment]
@Giovanni-Mattucci I'm having the same problem on Kubuntu 16.04. What did you upgrade to 1.2.0?

**Comment by Giovanni-Mattucci** [comment]
@ganiserb updated `grunt-sass`, but I had to go into the source template files and update it to avoid issues here: [https://github.com/whyleee/generator-powermvc/blob/master/app/templates/_package.json](https://github.com/whyleee/generator-powermvc/blob/master/app/templates/_package.json)
